version: '3'

services: 
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/usr/src
    depends_on: 
      - db
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: 'birdierigg'
      MYSQL_USER: 'api'
      MYSQL_PASSWORD: 'dinmamma'
      MYSQL_ROOT_PASSWORD: 'dinpappa'
    expose:
      - '3306'
    volumes:
      - rigg-db:/var/lib/mysql

volumes:
  rigg-db:
        